const commonWords = [
  "",
  "Ai-mrk",
  "ai-mrk",
  "Ajay Shukla",
  "ajay shukla",
  "apple",
  "banana",
  "cherry",
  "date",
  "elderberry",
  "algorithm",
  "binary",
  "compiler",
  "database",
  "encryption",
  "firewall",
  "graphics",
  "hardware",
  "interface",
  "javascript",
  "kernel",
  "linux",
  "machine",
  "network",
  "operating",
  "programming",
  "query",
  "router",
  "software",
  "template",
  "unicode",
  "virtual",
  "webpage",
  "xenon",
  "yield",
  "zombie",
  "array",
  "bytecode",
  "cache",
  "debugging",
  "ethernet",
  "firewire",
  "gigabyte",
  "hashing",
  "iteration",
  "java",
  "kernel",
  "library",
  "microchip",
  "networking",
  "overflow",
  "protocol",
  "quantum",
  "router",
  "syntax",
  "template",
  "unicode",
  "variable",
  "workflow",
  "xml",
  "yield",
  "algorithm",
  "bitwise",
  "cryptography",
  "debugging",
  "ethernet",
  "firewall",
  "graphics",
  "hyperlink",
  "integer",
  "javascript",
  "kernel",
  "linux",
  "microprocessor",
  "network",
  "operating",
  "programming",
  "query",
  "router",
  "socket",
  "template",
  "unicode",
  "virtual",
  "webpage",
  "xenon",
  "yield",
  "zip",
  "analog",
  "boolean",
  "compiler",
  "data",
  "encryption",
  "firewall",
  "graphics",
  "hash",
  "internet",
  "javascript",
  "kernel",
  "linux",
  "malware",
  "network",
  "operating",
  "programming",
  "query",
  "router",
  "server",
  "template",
  "unicode",
  "virtual",
  "webpage",
  "xenon",
  "yield",
  "zip",
  "Apple",
  "Banana",
  "Cherry",
  "Date",
  "Elderberry",
  "Algorithm",
  "Binary",
  "Compiler",
  "Database",
  "Encryption",
  "Firewall",
  "Graphics",
  "Hardware",
  "Interface",
  "Javascript",
  "Kernel",
  "Linux",
  "Machine",
  "Network",
  "Operating",
  "Programming",
  "Query",
  "Router",
  "Software",
  "Template",
  "Unicode",
  "Virtual",
  "Webpage",
  "Xenon",
  "Yield",
  "Zombie",
  "Array",
  "Bytecode",
  "Cache",
  "Debugging",
  "Ethernet",
  "Firewire",
  "Gigabyte",
  "Hashing",
  "Iteration",
  "Java",
  "Kernel",
  "Library",
  "Microchip",
  "Networking",
  "Overflow",
  "Protocol",
  "Quantum",
  "Router",
  "Syntax",
  "Template",
  "Unicode",
  "Variable",
  "Workflow",
  "XML",
  "Yield",
  "Algorithm",
  "Bitwise",
  "Cryptography",
  "Debugging",
  "Ethernet",
  "Firewall",
  "Graphics",
  "Hyperlink",
  "Integer",
  "Javascript",
  "Kernel",
  "Linux",
  "Microprocessor",
  "Network",
  "Operating",
  "Programming",
  "Query",
  "Router",
  "Socket",
  "Template",
  "Unicode",
  "Virtual",
  "Webpage",
  "Xenon",
  "Yield",
  "Zip",
  "Analog",
  "Boolean",
  "Compiler",
  "Data",
  "Encryption",
  "Firewall",
  "Graphics",
  "Hash",
  "Internet",
  "Javascript",
  "Kernel",
  "Linux",
  "Malware",
  "Network",
  "Operating",
  "Programming",
  "Query",
  "Router",
  "Server",
  "Template",
  "Unicode",
  "Virtual",
  "Webpage",
  "Xenon",
  "Yield",
  "Zip",
  "Hello",
  "Hi",
  "Hey",
  "Chatbot",
  "Assistant",
  "Help",
  "Information",
  "Answer",
  "Question",
  "How",
  "What",
  "Why",
  "When",
  "Where",
  "Who",
  "Can",
  "Tell",
  "Explain",
  "Assist",
  "Please",
  "Thanks",
  "Thank you",
  "Goodbye",
  "Start",
  "Stop",
  "Continue",
  "Yes",
  "No",
  "Maybe",
  "I",
  "You",
  "We",
  "They",
  "It",
  "Problem",
  "Issue",
  "Error",
  "Query",
  "Search",
  "Open",
  "Close",
  "Show",
  "Hide",
  "Menu",
  "Options",
  "Settings",
  "Language",
  "Cancel",
  "Done",
  "Next",
  "Back",
  "More",
  "Less",
  "Try",
  "Test",
  "Results",
  "Chat",
  "Conversation",
  "Bot",
  "User",
  "Input",
  "Output",
  "Response",
  "Request",
  "Requested",
  "Welcome",
  "Greeting",
  "Name",
  "Age",
  "Location",
  "Time",
  "Date",
  "Weather",
  "News",
  "Helpdesk",
  "Support",
  "FAQ",
  "FAQS",
  "Feature",
  "Function",
  "Capability",
  "Training",
  "Learning",
  "Understand",
  "Knowledge",
  "Database",
  "Update",
  "Upgrade",
  "Maintenance",
  "Bug",
  "Improvement",
  "Feedback",
  "Suggestion",
  "Analyze",
  "Report",
  "Metric",
  "Privacy",
  "Security",
  "Terms",
  "Hello",
  "Hi",
  "Hey",
  "Chatbot",
  "Assistant",
  "Help",
  "Information",
  "Answer",
  "Question",
  "How",
  "What",
  "Why",
  "When",
  "Where",
  "Who",
  "Can",
  "Tell",
  "Explain",
  "Assist",
  "Please",
  "Thanks",
  "Thank you",
  "Goodbye",
  "Start",
  "Stop",
  "Continue",
  "Yes",
  "No",
  "Maybe",
  "I",
  "You",
  "We",
  "They",
  "It",
  "Problem",
  "Issue",
  "Error",
  "Query",
  "Search",
  "Open",
  "Close",
  "Show",
  "Hide",
  "Menu",
  "Options",
  "Settings",
  "Language",
  "Cancel",
  "Done",
  "Next",
  "Back",
  "More",
  "Less",
  "Try",
  "Test",
  "Results",
  "Chat",
  "Conversation",
  "Bot",
  "User",
  "Input",
  "Output",
  "Response",
  "Request",
  "Requested",
  "Welcome",
  "Greeting",
  "Name",
  "Age",
  "Location",
  "Time",
  "Date",
  "Weather",
  "News",
  "Helpdesk",
  "Support",
  "FAQ",
  "FAQS",
  "Feature",
  "Function",
  "Capability",
  "Training",
  "Learning",
  "Understand",
  "Knowledge",
  "Database",
  "Update",
  "Upgrade",
  "Maintenance",
  "Bug",
  "Improvement",
  "Feedback",
  "Suggestion",
  "Analyze",
  "Report",
  "Metric",
  "Privacy",
  "Security",
  "Terms",
  "Format this text as a heading.",
  "Make this text bold.",
  "Italicize this phrase.",
  "Create a bullet list.",
  "Insert an image here.",
  "Add a hyperlink to this text.",
  "What's the shortcut for a code block?",
  "Indent this paragraph.",
  "Undo my last action.",
  "Redo what I just did.",
  "How do I insert a table?",
  "Show me available formatting options.",
  "Change the text color to blue.",
  "Preview my Markdown.",
  "Save my document.",
  "How do I export as HTML?",
  "Convert this list to numbered.",
  "Insert a horizontal rule.",
  "Change the font size.",
  "Clear all formatting.",

  "format this text as a heading",
  "make this text bold",
  "italicize this phrase",
  "create a bullet list",
  "insert an image here",
  "add a hyperlink to this text",
  "what's the shortcut for a code block",
  "indent this paragraph",
  "undo my last action",
  "redo what i just did",
  "how do i insert a table",
  "show me available formatting options",
  "change the text color to blue",
  "preview my markdown",
  "save my document",
  "how do i export as html",
  "convert this list to numbered",
  "insert a horizontal rule",
  "change the font size",
  "clear all formatting",
  "How are you",
  "how are you",
  "who",
  "Who"
];
export {commonWords};